# Generated by Django 5.2.7 on 2025-11-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tg_chat_id",
            field=models.CharField(
                default=1, max_length=50, verbose_name="Телеграм chat-id"
            ),
            preserve_default=False,
        ),
    ]
