# Generated by Django 5.2.7 on 2025-11-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_tg_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="tg_chat_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Телеграм chat-id"
            ),
        ),
    ]
