# Generated by Django 5.2.7 on 2025-11-01 19:27

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(verbose_name="Место выполнения привычки")),
                (
                    "period",
                    models.TimeField(
                        verbose_name="Время когда необходимо выполнять привычку"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        verbose_name="Действие которое представляет из себя привычка"
                    ),
                ),
                (
                    "periodicity",
                    models.IntegerField(
                        default=1, verbose_name="Периодичность выполнения привычки"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        verbose_name="Награда за выполнение полезной привычки"
                    ),
                ),
                (
                    "time_to_complete",
                    models.DurationField(
                        default=datetime.timedelta(seconds=120),
                        verbose_name="Время на выполнение привычки",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="Статус публикации привычки"
                    ),
                ),
                (
                    "pleasant_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rewarded_habits",
                        to="habits.habit",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="antecedent_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
