# Generated by Django 5.2.7 on 2025-11-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="pleasant_habit",
        ),
        migrations.AddField(
            model_name="habit",
            name="is_pleasant_habit",
            field=models.BooleanField(
                default=True, verbose_name="Признак приятной привычки"
            ),
        ),
    ]
