# Generated by Django 5.2.7 on 2025-11-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_remove_habit_pleasant_habit_habit_is_pleasant_habit"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_sent_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата последнего напоминания"
            ),
        ),
    ]
