# Generated by Django 5.2.7 on 2025-11-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_habit_last_sent_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["period"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
