# Generated by Django 5.2.7 on 2025-11-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habit_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                null=True,
                verbose_name="Награда за выполнение полезной привычки",
            ),
        ),
    ]
